# -*- coding: utf-8 -*-
"""Llama3.2_(1B_and_3B)-Conversational.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(1B_and_3B)-Conversational.ipynb
"""

import sys

# 1. Install Necessary Libraries
!{sys.executable} -m pip install accelerate bitsandbytes
!{sys.executable} -m pip install pypdf

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from pypdf import PdfReader

# 2. Load Qwen Model and Tokenizer
# Attempting to load Qwen2-7B-Instruct as requested, despite previous errors with this model size.
model_id = "Qwen/Qwen2-7B-Instruct"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map='auto',
    trust_remote_code=True
)
print(f"✓ Tokenizer and model '{model_id}' loaded successfully with 4-bit quantization.")

# 3. Read Prompt and PDF Content
pdf_texts = []
for pdf_file in ['1.pdf', '2.pdf', '3.pdf']:
    reader = PdfReader(pdf_file)
    text = ""
    for page in reader.pages:
        extracted_text = page.extract_text()
        if extracted_text:
            text += extracted_text
    pdf_texts.append(text)

with open('prompt.txt', 'r') as f:
    prompt_text = f.read()

print("✓ PDF files and prompt.txt read successfully.")

# 4. Combine and Truncate Input (for each PDF individually)
max_seq_length = tokenizer.model_max_length
prompt_tokens = tokenizer.encode(prompt_text, add_special_tokens=False)
prompt_token_length = len(prompt_tokens)
reserved_tokens = 50
target_total_input_tokens = 4000
available_pdf_token_budget = target_total_input_tokens - prompt_token_length - reserved_tokens

if available_pdf_token_budget < 0:
    available_pdf_token_budget = 0

print(f"✓ PDF content preparation parameters calculated. Available PDF token budget per PDF for generation: {available_pdf_token_budget}")

# 5. Generate Response for each PDF and Save Output
for i, current_pdf_content in enumerate(pdf_texts):
    print(f"\n--- Processing PDF {i+1} ---")

    current_pdf_tokens = tokenizer.encode(current_pdf_content, add_special_tokens=False)

    if len(current_pdf_tokens) > available_pdf_token_budget:
        truncated_pdf_tokens = current_pdf_tokens[:available_pdf_token_budget]
        current_pdf_content_truncated = tokenizer.decode(truncated_pdf_tokens, skip_special_tokens=True)
        print(f"Truncated PDF {i+1} content from {len(current_pdf_tokens)} tokens to {len(truncated_pdf_tokens)} tokens.")
    else:
        current_pdf_content_truncated = current_pdf_content
        print(f"PDF {i+1} content fits within the budget: {len(current_pdf_tokens)} tokens.")

    full_input_for_current_pdf = f"{prompt_text}\n\n{current_pdf_content_truncated}"
    print(f"✓ Full input for PDF {i+1} created. Total tokens (approx): {len(tokenizer.encode(full_input_for_current_pdf))}")

    messages = [
        {"role": "user", "content": full_input_for_current_pdf}
    ]
    formatted_input = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    inputs = tokenizer(formatted_input, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)

    output_filename = f'model_output_{i+1}.txt'
    with open(output_filename, 'w') as f:
        f.write(response)

    print(f"✓ Response for PDF {i+1} generated and saved to {output_filename}")
    print(f"Output preview for PDF {i+1}:\n{response[:500]}...")

print("\n--- All PDFs processed. ---")